### ISSUE TITLE
how to add lcov and gcovr to Ubuntu base image or gcc 

### ISSUE THREAD

**Issue by rubinliudongpo** [BrainTwister/docker-devel-env#6]
I want to add lcov and gcovr to code coverage, will you help me on this?

**Comment by BerndDoser** [comment]
I have added two modules for gcovr and lcov. With it you can build your favorite development container by writing a file `my-images.yml`:

```
---
images:
 - ['ubuntu-18.04', 'cmake-3.12', 'gcc-7', 'gcovr-4.1']
 - ['ubuntu-18.04', 'cmake-3.12', 'gcc-7', 'lcof-1.8']
```
and build it with:
```
./build.py -i my-images.yml
```

**Comment by rubinliudongpo** [comment]
Thanks you
